//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Rsdn.RsdnNntp.Public.RsdnService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service2Soap", Namespace="http://rsdn.ru/ws2/")]
    public partial class Service2 : Microsoft.Web.Services2.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback PostMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormattedArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArticleByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormattedArticleByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArticleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArticleListFromDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service2() {
            this.Url = global::Rsdn.RsdnNntp.Public.Properties.Settings.Default.RsdnDataPublicProvider_RsdnService_Service2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostMessageCompletedEventHandler PostMessageCompleted;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event GetUserInfoByIDCompletedEventHandler GetUserInfoByIDCompleted;
        
        /// <remarks/>
        public event GetGroupListCompletedEventHandler GetGroupListCompleted;
        
        /// <remarks/>
        public event GroupInfoCompletedEventHandler GroupInfoCompleted;
        
        /// <remarks/>
        public event GetArticleCompletedEventHandler GetArticleCompleted;
        
        /// <remarks/>
        public event GetFormattedArticleCompletedEventHandler GetFormattedArticleCompleted;
        
        /// <remarks/>
        public event GetArticleByIDCompletedEventHandler GetArticleByIDCompleted;
        
        /// <remarks/>
        public event GetFormattedArticleByIDCompletedEventHandler GetFormattedArticleByIDCompleted;
        
        /// <remarks/>
        public event ArticleListCompletedEventHandler ArticleListCompleted;
        
        /// <remarks/>
        public event ArticleListFromDateCompletedEventHandler ArticleListFromDateCompleted;
        
        /// <remarks/>
        public event AuthenticationCompletedEventHandler AuthenticationCompleted;
        
        /// <remarks/>
        public event GetLinkCompletedEventHandler GetLinkCompleted;
        
        /// <remarks/>
        public event PostFileCompletedEventHandler PostFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/PostMessage", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostMessage(int mid, string group, string subject, string message) {
            this.Invoke("PostMessage", new object[] {
                        mid,
                        group,
                        subject,
                        message});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostMessage(int mid, string group, string subject, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostMessage", new object[] {
                        mid,
                        group,
                        subject,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostMessage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void PostMessageAsync(int mid, string group, string subject, string message) {
            this.PostMessageAsync(mid, group, subject, message, null);
        }
        
        /// <remarks/>
        public void PostMessageAsync(int mid, string group, string subject, string message, object userState) {
            if ((this.PostMessageOperationCompleted == null)) {
                this.PostMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostMessageOperationCompleted);
            }
            this.InvokeAsync("PostMessage", new object[] {
                        mid,
                        group,
                        subject,
                        message}, this.PostMessageOperationCompleted, userState);
        }
        
        private void OnPostMessageOperationCompleted(object arg) {
            if ((this.PostMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetUserInfo", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfo() {
            object[] results = this.Invoke("GetUserInfo", new object[0]);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserInfo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public UserInfo EndGetUserInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync() {
            this.GetUserInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[0], this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetUserInfoByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfoByID(int id) {
            object[] results = this.Invoke("GetUserInfoByID", new object[] {
                        id});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfoByID(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserInfoByID", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserInfo EndGetUserInfoByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByIDAsync(int id) {
            this.GetUserInfoByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByIDAsync(int id, object userState) {
            if ((this.GetUserInfoByIDOperationCompleted == null)) {
                this.GetUserInfoByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByIDOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByID", new object[] {
                        id}, this.GetUserInfoByIDOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByIDOperationCompleted(object arg) {
            if ((this.GetUserInfoByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByIDCompleted(this, new GetUserInfoByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetGroupList", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public group_list GetGroupList(System.DateTime dtc) {
            object[] results = this.Invoke("GetGroupList", new object[] {
                        dtc});
            return ((group_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGroupList(System.DateTime dtc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGroupList", new object[] {
                        dtc}, callback, asyncState);
        }
        
        /// <remarks/>
        public group_list EndGetGroupList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((group_list)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupListAsync(System.DateTime dtc) {
            this.GetGroupListAsync(dtc, null);
        }
        
        /// <remarks/>
        public void GetGroupListAsync(System.DateTime dtc, object userState) {
            if ((this.GetGroupListOperationCompleted == null)) {
                this.GetGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupListOperationCompleted);
            }
            this.InvokeAsync("GetGroupList", new object[] {
                        dtc}, this.GetGroupListOperationCompleted, userState);
        }
        
        private void OnGetGroupListOperationCompleted(object arg) {
            if ((this.GetGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupListCompleted(this, new GetGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GroupInfo", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public group GroupInfo(string name) {
            object[] results = this.Invoke("GroupInfo", new object[] {
                        name});
            return ((group)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroupInfo(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GroupInfo", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public group EndGroupInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((group)(results[0]));
        }
        
        /// <remarks/>
        public void GroupInfoAsync(string name) {
            this.GroupInfoAsync(name, null);
        }
        
        /// <remarks/>
        public void GroupInfoAsync(string name, object userState) {
            if ((this.GroupInfoOperationCompleted == null)) {
                this.GroupInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupInfoOperationCompleted);
            }
            this.InvokeAsync("GroupInfo", new object[] {
                        name}, this.GroupInfoOperationCompleted, userState);
        }
        
        private void OnGroupInfoOperationCompleted(object arg) {
            if ((this.GroupInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupInfoCompleted(this, new GroupInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetArticle", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetArticle(string group, int number) {
            object[] results = this.Invoke("GetArticle", new object[] {
                        group,
                        number});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetArticle(string group, int number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetArticle", new object[] {
                        group,
                        number}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetArticle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public void GetArticleAsync(string group, int number) {
            this.GetArticleAsync(group, number, null);
        }
        
        /// <remarks/>
        public void GetArticleAsync(string group, int number, object userState) {
            if ((this.GetArticleOperationCompleted == null)) {
                this.GetArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArticleOperationCompleted);
            }
            this.InvokeAsync("GetArticle", new object[] {
                        group,
                        number}, this.GetArticleOperationCompleted, userState);
        }
        
        private void OnGetArticleOperationCompleted(object arg) {
            if ((this.GetArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArticleCompleted(this, new GetArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetFormattedArticle", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetFormattedArticle(string group, int number) {
            object[] results = this.Invoke("GetFormattedArticle", new object[] {
                        group,
                        number});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFormattedArticle(string group, int number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFormattedArticle", new object[] {
                        group,
                        number}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetFormattedArticle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormattedArticleAsync(string group, int number) {
            this.GetFormattedArticleAsync(group, number, null);
        }
        
        /// <remarks/>
        public void GetFormattedArticleAsync(string group, int number, object userState) {
            if ((this.GetFormattedArticleOperationCompleted == null)) {
                this.GetFormattedArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormattedArticleOperationCompleted);
            }
            this.InvokeAsync("GetFormattedArticle", new object[] {
                        group,
                        number}, this.GetFormattedArticleOperationCompleted, userState);
        }
        
        private void OnGetFormattedArticleOperationCompleted(object arg) {
            if ((this.GetFormattedArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormattedArticleCompleted(this, new GetFormattedArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetArticleByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetArticleByID(int mid) {
            object[] results = this.Invoke("GetArticleByID", new object[] {
                        mid});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetArticleByID(int mid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetArticleByID", new object[] {
                        mid}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetArticleByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public void GetArticleByIDAsync(int mid) {
            this.GetArticleByIDAsync(mid, null);
        }
        
        /// <remarks/>
        public void GetArticleByIDAsync(int mid, object userState) {
            if ((this.GetArticleByIDOperationCompleted == null)) {
                this.GetArticleByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArticleByIDOperationCompleted);
            }
            this.InvokeAsync("GetArticleByID", new object[] {
                        mid}, this.GetArticleByIDOperationCompleted, userState);
        }
        
        private void OnGetArticleByIDOperationCompleted(object arg) {
            if ((this.GetArticleByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArticleByIDCompleted(this, new GetArticleByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetFormattedArticleByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetFormattedArticleByID(int mid) {
            object[] results = this.Invoke("GetFormattedArticleByID", new object[] {
                        mid});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFormattedArticleByID(int mid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFormattedArticleByID", new object[] {
                        mid}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetFormattedArticleByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormattedArticleByIDAsync(int mid) {
            this.GetFormattedArticleByIDAsync(mid, null);
        }
        
        /// <remarks/>
        public void GetFormattedArticleByIDAsync(int mid, object userState) {
            if ((this.GetFormattedArticleByIDOperationCompleted == null)) {
                this.GetFormattedArticleByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormattedArticleByIDOperationCompleted);
            }
            this.InvokeAsync("GetFormattedArticleByID", new object[] {
                        mid}, this.GetFormattedArticleByIDOperationCompleted, userState);
        }
        
        private void OnGetFormattedArticleByIDOperationCompleted(object arg) {
            if ((this.GetFormattedArticleByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormattedArticleByIDCompleted(this, new GetFormattedArticleByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/ArticleList", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article_list ArticleList(string group, int first, int last) {
            object[] results = this.Invoke("ArticleList", new object[] {
                        group,
                        first,
                        last});
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginArticleList(string group, int first, int last, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ArticleList", new object[] {
                        group,
                        first,
                        last}, callback, asyncState);
        }
        
        /// <remarks/>
        public article_list EndArticleList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public void ArticleListAsync(string group, int first, int last) {
            this.ArticleListAsync(group, first, last, null);
        }
        
        /// <remarks/>
        public void ArticleListAsync(string group, int first, int last, object userState) {
            if ((this.ArticleListOperationCompleted == null)) {
                this.ArticleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArticleListOperationCompleted);
            }
            this.InvokeAsync("ArticleList", new object[] {
                        group,
                        first,
                        last}, this.ArticleListOperationCompleted, userState);
        }
        
        private void OnArticleListOperationCompleted(object arg) {
            if ((this.ArticleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArticleListCompleted(this, new ArticleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/ArticleListFromDate", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article_list ArticleListFromDate(string[] groups, System.DateTime startDate) {
            object[] results = this.Invoke("ArticleListFromDate", new object[] {
                        groups,
                        startDate});
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginArticleListFromDate(string[] groups, System.DateTime startDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ArticleListFromDate", new object[] {
                        groups,
                        startDate}, callback, asyncState);
        }
        
        /// <remarks/>
        public article_list EndArticleListFromDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public void ArticleListFromDateAsync(string[] groups, System.DateTime startDate) {
            this.ArticleListFromDateAsync(groups, startDate, null);
        }
        
        /// <remarks/>
        public void ArticleListFromDateAsync(string[] groups, System.DateTime startDate, object userState) {
            if ((this.ArticleListFromDateOperationCompleted == null)) {
                this.ArticleListFromDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArticleListFromDateOperationCompleted);
            }
            this.InvokeAsync("ArticleListFromDate", new object[] {
                        groups,
                        startDate}, this.ArticleListFromDateOperationCompleted, userState);
        }
        
        private void OnArticleListFromDateOperationCompleted(object arg) {
            if ((this.ArticleListFromDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArticleListFromDateCompleted(this, new ArticleListFromDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/Authentication", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Authentication() {
            this.Invoke("Authentication", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthentication(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authentication", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAuthentication(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AuthenticationAsync() {
            this.AuthenticationAsync(null);
        }
        
        /// <remarks/>
        public void AuthenticationAsync(object userState) {
            if ((this.AuthenticationOperationCompleted == null)) {
                this.AuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticationOperationCompleted);
            }
            this.InvokeAsync("Authentication", new object[0], this.AuthenticationOperationCompleted, userState);
        }
        
        private void OnAuthenticationOperationCompleted(object arg) {
            if ((this.AuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetLink", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public link GetLink(string link, LinkType type) {
            object[] results = this.Invoke("GetLink", new object[] {
                        link,
                        type});
            return ((link)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLink(string link, LinkType type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLink", new object[] {
                        link,
                        type}, callback, asyncState);
        }
        
        /// <remarks/>
        public link EndGetLink(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((link)(results[0]));
        }
        
        /// <remarks/>
        public void GetLinkAsync(string link, LinkType type) {
            this.GetLinkAsync(link, type, null);
        }
        
        /// <remarks/>
        public void GetLinkAsync(string link, LinkType type, object userState) {
            if ((this.GetLinkOperationCompleted == null)) {
                this.GetLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinkOperationCompleted);
            }
            this.InvokeAsync("GetLink", new object[] {
                        link,
                        type}, this.GetLinkOperationCompleted, userState);
        }
        
        private void OnGetLinkOperationCompleted(object arg) {
            if ((this.GetLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinkCompleted(this, new GetLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/PostFile", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostFile(string fileName, string contentType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content) {
            object[] results = this.Invoke("PostFile", new object[] {
                        fileName,
                        contentType,
                        content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostFile(string fileName, string contentType, byte[] content, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostFile", new object[] {
                        fileName,
                        contentType,
                        content}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPostFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostFileAsync(string fileName, string contentType, byte[] content) {
            this.PostFileAsync(fileName, contentType, content, null);
        }
        
        /// <remarks/>
        public void PostFileAsync(string fileName, string contentType, byte[] content, object userState) {
            if ((this.PostFileOperationCompleted == null)) {
                this.PostFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostFileOperationCompleted);
            }
            this.InvokeAsync("PostFile", new object[] {
                        fileName,
                        contentType,
                        content}, this.PostFileOperationCompleted, userState);
        }
        
        private void OnPostFileOperationCompleted(object arg) {
            if ((this.PostFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostFileCompleted(this, new PostFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class UserInfo {
        
        private UserRole userRoleField;
        
        private int idField;
        
        private string nameField;
        
        private string passwordField;
        
        private string emailField;
        
        private bool activatedField;
        
        private string nickField;
        
        private string publicEmailField;
        
        private string realNameField;
        
        private string homePageField;
        
        private string specializationField;
        
        private bool sendMailField;
        
        private MessageFormat messageFormatField;
        
        private ForwardType forwardTypeField;
        
        private bool stopMailField;
        
        private string adminMessageField;
        
        private bool flatField;
        
        private bool defaultFlatField;
        
        private int pageCountField;
        
        private string pictureField;
        
        private string whereFromField;
        
        private string originField;
        
        private string ipField;
        
        private int personRateField;
        
        private int totalRateField;
        
        private bool isCrawlerField;
        
        private System.DateTime banDateField;
        
        private string titleField;
        
        private int titleColorField;
        
        /// <remarks/>
        public UserRole UserRole {
            get {
                return this.userRoleField;
            }
            set {
                this.userRoleField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool Activated {
            get {
                return this.activatedField;
            }
            set {
                this.activatedField = value;
            }
        }
        
        /// <remarks/>
        public string Nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public string PublicEmail {
            get {
                return this.publicEmailField;
            }
            set {
                this.publicEmailField = value;
            }
        }
        
        /// <remarks/>
        public string RealName {
            get {
                return this.realNameField;
            }
            set {
                this.realNameField = value;
            }
        }
        
        /// <remarks/>
        public string HomePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
            }
        }
        
        /// <remarks/>
        public string Specialization {
            get {
                return this.specializationField;
            }
            set {
                this.specializationField = value;
            }
        }
        
        /// <remarks/>
        public bool SendMail {
            get {
                return this.sendMailField;
            }
            set {
                this.sendMailField = value;
            }
        }
        
        /// <remarks/>
        public MessageFormat MessageFormat {
            get {
                return this.messageFormatField;
            }
            set {
                this.messageFormatField = value;
            }
        }
        
        /// <remarks/>
        public ForwardType ForwardType {
            get {
                return this.forwardTypeField;
            }
            set {
                this.forwardTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool StopMail {
            get {
                return this.stopMailField;
            }
            set {
                this.stopMailField = value;
            }
        }
        
        /// <remarks/>
        public string AdminMessage {
            get {
                return this.adminMessageField;
            }
            set {
                this.adminMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool Flat {
            get {
                return this.flatField;
            }
            set {
                this.flatField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultFlat {
            get {
                return this.defaultFlatField;
            }
            set {
                this.defaultFlatField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public string Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        public string WhereFrom {
            get {
                return this.whereFromField;
            }
            set {
                this.whereFromField = value;
            }
        }
        
        /// <remarks/>
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public int PersonRate {
            get {
                return this.personRateField;
            }
            set {
                this.personRateField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRate {
            get {
                return this.totalRateField;
            }
            set {
                this.totalRateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCrawler {
            get {
                return this.isCrawlerField;
            }
            set {
                this.isCrawlerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BanDate {
            get {
                return this.banDateField;
            }
            set {
                this.banDateField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public int TitleColor {
            get {
                return this.titleColorField;
            }
            set {
                this.titleColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum UserRole {
        
        /// <remarks/>
        Admin,
        
        /// <remarks/>
        Moderator,
        
        /// <remarks/>
        TeamMember,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Expert,
        
        /// <remarks/>
        Anonym,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum MessageFormat {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Text = 2,
        
        /// <remarks/>
        Html = 4,
        
        /// <remarks/>
        TextHtml = 8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum ForwardType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Private,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class link {
        
        private string errorField;
        
        private string urlField;
        
        private string nameField;
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class article_list {
        
        private string errorField;
        
        private string postfixField;
        
        private System.DateTime dateField;
        
        private article[] articlesField;
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string postfix {
            get {
                return this.postfixField;
            }
            set {
                this.postfixField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public article[] articles {
            get {
                return this.articlesField;
            }
            set {
                this.articlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class article {
        
        private string errorField;
        
        private string postfixField;
        
        private string idField;
        
        private string pidField;
        
        private string gidField;
        
        private int numField;
        
        private string authorField;
        
        private string authoridField;
        
        private System.DateTime dateField;
        
        private string subjectField;
        
        private string messageField;
        
        private string fmtmessageField;
        
        private string userTypeField;
        
        private int userColorField;
        
        private string homePageField;
        
        private string groupField;
        
        private bool smileField;
        
        public article() {
            this.userColorField = 0;
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string postfix {
            get {
                return this.postfixField;
            }
            set {
                this.postfixField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        public string gid {
            get {
                return this.gidField;
            }
            set {
                this.gidField = value;
            }
        }
        
        /// <remarks/>
        public int num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string authorid {
            get {
                return this.authoridField;
            }
            set {
                this.authoridField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string fmtmessage {
            get {
                return this.fmtmessageField;
            }
            set {
                this.fmtmessageField = value;
            }
        }
        
        /// <remarks/>
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int userColor {
            get {
                return this.userColorField;
            }
            set {
                this.userColorField = value;
            }
        }
        
        /// <remarks/>
        public string homePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
            }
        }
        
        /// <remarks/>
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public bool smile {
            get {
                return this.smileField;
            }
            set {
                this.smileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class group {
        
        private string errorField;
        
        private string nameField;
        
        private System.DateTime createdField;
        
        private int numberField;
        
        private int firstField;
        
        private int lastField;
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public int first {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        public int last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public partial class group_list {
        
        private System.DateTime dateField;
        
        private string errorField;
        
        private group[] groupsField;
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public group[] groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum LinkType {
        
        /// <remarks/>
        MSDN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void PostMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetUserInfoByIDCompletedEventHandler(object sender, GetUserInfoByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetGroupListCompletedEventHandler(object sender, GetGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public group_list Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((group_list)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GroupInfoCompletedEventHandler(object sender, GroupInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public group Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((group)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetArticleCompletedEventHandler(object sender, GetArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFormattedArticleCompletedEventHandler(object sender, GetFormattedArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormattedArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormattedArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetArticleByIDCompletedEventHandler(object sender, GetArticleByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArticleByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArticleByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFormattedArticleByIDCompletedEventHandler(object sender, GetFormattedArticleByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormattedArticleByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormattedArticleByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ArticleListCompletedEventHandler(object sender, ArticleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArticleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArticleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article_list Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article_list)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ArticleListFromDateCompletedEventHandler(object sender, ArticleListFromDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArticleListFromDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArticleListFromDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public article_list Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((article_list)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AuthenticationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLinkCompletedEventHandler(object sender, GetLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public link Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((link)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void PostFileCompletedEventHandler(object sender, PostFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591