using Microsoft.Web.Services2;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace Rsdn.RsdnNntp.RsdnService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service2Soap", Namespace="http://rsdn.ru/ws2/")]
    public class Service2 : WebServicesClientProtocol {
        
        /// <remarks/>
        public Service2() {
            this.Url = "http://rsdn.ru/ws/service2.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/PostMessage", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostMessage(int mid, string group, string subject, string message) {
            this.Invoke("PostMessage", new object[] {
                        mid,
                        group,
                        subject,
                        message});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostMessage(int mid, string group, string subject, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostMessage", new object[] {
                        mid,
                        group,
                        subject,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostMessage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetUserInfo", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfo() {
            object[] results = this.Invoke("GetUserInfo", new object[0]);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserInfo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public UserInfo EndGetUserInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetUserInfoByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfoByID(int id) {
            object[] results = this.Invoke("GetUserInfoByID", new object[] {
                        id});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfoByID(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserInfoByID", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserInfo EndGetUserInfoByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetGroupList", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public group_list GetGroupList(System.DateTime dtc) {
            object[] results = this.Invoke("GetGroupList", new object[] {
                        dtc});
            return ((group_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGroupList(System.DateTime dtc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGroupList", new object[] {
                        dtc}, callback, asyncState);
        }
        
        /// <remarks/>
        public group_list EndGetGroupList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((group_list)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GroupInfo", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public group GroupInfo(string name) {
            object[] results = this.Invoke("GroupInfo", new object[] {
                        name});
            return ((group)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroupInfo(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GroupInfo", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public group EndGroupInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((group)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetArticle", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetArticle(string group, int number) {
            object[] results = this.Invoke("GetArticle", new object[] {
                        group,
                        number});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetArticle(string group, int number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetArticle", new object[] {
                        group,
                        number}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetArticle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetFormattedArticle", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetFormattedArticle(string group, int number) {
            object[] results = this.Invoke("GetFormattedArticle", new object[] {
                        group,
                        number});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFormattedArticle(string group, int number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFormattedArticle", new object[] {
                        group,
                        number}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetFormattedArticle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetArticleByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetArticleByID(int mid) {
            object[] results = this.Invoke("GetArticleByID", new object[] {
                        mid});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetArticleByID(int mid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetArticleByID", new object[] {
                        mid}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetArticleByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetFormattedArticleByID", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article GetFormattedArticleByID(int mid) {
            object[] results = this.Invoke("GetFormattedArticleByID", new object[] {
                        mid});
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFormattedArticleByID(int mid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFormattedArticleByID", new object[] {
                        mid}, callback, asyncState);
        }
        
        /// <remarks/>
        public article EndGetFormattedArticleByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/ArticleList", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article_list ArticleList(string group, int first, int last) {
            object[] results = this.Invoke("ArticleList", new object[] {
                        group,
                        first,
                        last});
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginArticleList(string group, int first, int last, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ArticleList", new object[] {
                        group,
                        first,
                        last}, callback, asyncState);
        }
        
        /// <remarks/>
        public article_list EndArticleList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/ArticleListFromDate", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public article_list ArticleListFromDate(string[] groups, System.DateTime startDate) {
            object[] results = this.Invoke("ArticleListFromDate", new object[] {
                        groups,
                        startDate});
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginArticleListFromDate(string[] groups, System.DateTime startDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ArticleListFromDate", new object[] {
                        groups,
                        startDate}, callback, asyncState);
        }
        
        /// <remarks/>
        public article_list EndArticleListFromDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((article_list)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/Authentication", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Authentication() {
            this.Invoke("Authentication", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthentication(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authentication", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAuthentication(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/GetLink", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public link GetLink(string link, LinkType type) {
            object[] results = this.Invoke("GetLink", new object[] {
                        link,
                        type});
            return ((link)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLink(string link, LinkType type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLink", new object[] {
                        link,
                        type}, callback, asyncState);
        }
        
        /// <remarks/>
        public link EndGetLink(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((link)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/ws2/PostFile", RequestNamespace="http://rsdn.ru/ws2/", ResponseNamespace="http://rsdn.ru/ws2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostFile(string fileName, string contentType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] System.Byte[] content) {
            object[] results = this.Invoke("PostFile", new object[] {
                        fileName,
                        contentType,
                        content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostFile(string fileName, string contentType, System.Byte[] content, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostFile", new object[] {
                        fileName,
                        contentType,
                        content}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPostFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class UserInfo {
        
        /// <remarks/>
        public UserRole UserRole;
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public bool Activated;
        
        /// <remarks/>
        public string Nick;
        
        /// <remarks/>
        public string PublicEmail;
        
        /// <remarks/>
        public string RealName;
        
        /// <remarks/>
        public string HomePage;
        
        /// <remarks/>
        public string Specialization;
        
        /// <remarks/>
        public bool SendMail;
        
        /// <remarks/>
        public MessageFormat MessageFormat;
        
        /// <remarks/>
        public ForwardType ForwardType;
        
        /// <remarks/>
        public bool StopMail;
        
        /// <remarks/>
        public string AdminMessage;
        
        /// <remarks/>
        public bool Flat;
        
        /// <remarks/>
        public bool DefaultFlat;
        
        /// <remarks/>
        public int PageCount;
        
        /// <remarks/>
        public string Picture;
        
        /// <remarks/>
        public string WhereFrom;
        
        /// <remarks/>
        public string Origin;
        
        /// <remarks/>
        public string IP;
        
        /// <remarks/>
        public int PersonRate;
        
        /// <remarks/>
        public int TotalRate;
        
        /// <remarks/>
        public bool IsCrawler;
        
        /// <remarks/>
        public System.DateTime BanDate;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public int TitleColor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum UserRole {
        
        /// <remarks/>
        Admin,
        
        /// <remarks/>
        Moderator,
        
        /// <remarks/>
        TeamMember,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Expert,
        
        /// <remarks/>
        Anonym,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    [System.FlagsAttribute()]
    public enum MessageFormat {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Text = 2,
        
        /// <remarks/>
        Html = 4,
        
        /// <remarks/>
        TextHtml = 8,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum ForwardType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Private,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class link {
        
        /// <remarks/>
        public string error;
        
        /// <remarks/>
        public string url;
        
        /// <remarks/>
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class article_list {
        
        /// <remarks/>
        public string error;
        
        /// <remarks/>
        public string postfix;
        
        /// <remarks/>
        public System.DateTime date;
        
        /// <remarks/>
        public article[] articles;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class article {
        
        /// <remarks/>
        public string error;
        
        /// <remarks/>
        public string postfix;
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        public string pid;
        
        /// <remarks/>
        public string gid;
        
        /// <remarks/>
        public int num;
        
        /// <remarks/>
        public string author;
        
        /// <remarks/>
        public string authorid;
        
        /// <remarks/>
        public System.DateTime date;
        
        /// <remarks/>
        public string subject;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string fmtmessage;
        
        /// <remarks/>
        public string userType;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int userColor = 0;
        
        /// <remarks/>
        public string homePage;
        
        /// <remarks/>
        public string group;
        
        /// <remarks/>
        public bool smile;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class group {
        
        /// <remarks/>
        public string error;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public System.DateTime created;
        
        /// <remarks/>
        public int number;
        
        /// <remarks/>
        public int first;
        
        /// <remarks/>
        public int last;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public class group_list {
        
        /// <remarks/>
        public System.DateTime date;
        
        /// <remarks/>
        public string error;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public group[] groups;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/ws2/")]
    public enum LinkType {
        
        /// <remarks/>
        MSDN,
    }
}
